# Android 12+ UI FrameTimeline. Does not establish SurfaceView frame support.
duration_ms: 20000
buffers { size_kb: 8192 fill_policy: DISCARD }
data_sources { config { name: "android.surfaceflinger.frametimeline" } }
data_sources {
  config {
    name: "linux.process_stats"
    process_stats_config { scan_all_processes_on_start: true }
  }
}
